"""Add shared synthetic paper trading account and order ledger"""
from alembic import op
import sqlalchemy as sa

revision = '5fa787f9511c'
down_revision = 'c435d4e5fa97'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cash_cents', sa.BigInteger(), nullable=False),
    sa.Column('cursor', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('cash_cents >= 0'),
    sa.CheckConstraint('cursor >= 0 AND cursor < 120'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_cents', sa.Integer(), nullable=True),
    sa.Column('fill_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('filled_at', sa.String(), nullable=True),
    sa.Column('session_index', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.CheckConstraint("side IN ('buy','sell')"),
    sa.CheckConstraint("status IN ('open','filled','cancelled','expired','settled')"),
    sa.CheckConstraint('quantity > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.execute("INSERT INTO paper_accounts (id, cash_cents, cursor, version) VALUES ('shared-pilot', 10000000, 60, 0)")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_orders')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
