"""Enforce exact dated company facility relationships"""
from alembic import op
import sqlalchemy as sa

revision = '6d0761b91504'
down_revision = 'ba950f257a0e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_facility_relationship',
    sa.Column('relationship_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('evidence_reference', sa.Text(), nullable=False),
    sa.Column('percentage', sa.Numeric(30, 6).with_variant(sa.String(40), 'sqlite'), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint("role IN ('OWNS','OPERATES')", name='ck_relationship_role'),
    sa.CheckConstraint('percentage IS NULL OR (CAST(percentage AS NUMERIC) >= 0 AND CAST(percentage AS NUMERIC) <= 100)', name='ck_relationship_share'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_relationship_interval'),
    sa.ForeignKeyConstraint(['company_id'], ['company.entity_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_version.document_id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.entity_id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    from datetime import date
    from decimal import Decimal
    bind=op.get_bind()
    legacy=sa.Table('relationships',sa.MetaData(),autoload_with=bind)
    target=sa.Table('company_facility_relationship',sa.MetaData(),autoload_with=bind)
    for row in bind.execute(sa.select(legacy)).mappings():
        share=Decimal(str(row['percentage'])) if row['percentage'] is not None else None
        bind.execute(target.insert().values(relationship_id=row['id'],company_id=row['company_id'],facility_id=row['facility_id'],document_id=row['document_id'],role=row['role'],evidence_reference='Document overall (legacy)',percentage=str(share) if bind.dialect.name=='sqlite' and share is not None else share,valid_from=date.fromisoformat(row['valid_from']),valid_to=date.fromisoformat(row['valid_to']) if row['valid_to'] else None))
    op.execute("CREATE VIEW capacity_observation AS SELECT o.*, d.normalized_value AS exact_value FROM observations o JOIN observation_detail d ON d.observation_id=o.id WHERE o.attribute='capacity'")
    op.execute("CREATE VIEW status_observation AS SELECT * FROM observations WHERE attribute='status'")
    op.execute("CREATE VIEW facility_alias AS SELECT a.* FROM entity_alias a JOIN entities e ON e.id=a.entity_id WHERE e.kind='facility'")


def downgrade():
    op.execute('DROP VIEW facility_alias')
    op.execute('DROP VIEW status_observation')
    op.execute('DROP VIEW capacity_observation')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_facility_relationship')
    # ### end Alembic commands ###
