"""Initial industrial evidence and market schema"""
from alembic import op
import sqlalchemy as sa

revision = '9a4e590703d9'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.CheckConstraint("kind IN ('company','facility')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('access_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'original_url', 'content_hash'),
    sa.UniqueConstraint('source_id', 'original_url', 'version')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('selected_entity_id', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['selected_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('contract_code', sa.String(), nullable=True),
    sa.Column('prompt_date', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('price_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('effective_at', sa.String(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('evidence_reference', sa.String(), nullable=False),
    sa.CheckConstraint('open_interest IS NULL OR open_interest >= 0'),
    sa.CheckConstraint('volume IS NULL OR volume >= 0'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_observations_effective_at'), ['effective_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_observations_instrument'), ['instrument'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('reported_value', sa.String(), nullable=False),
    sa.Column('reported_unit', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('normalized_unit', sa.String(), nullable=True),
    sa.Column('valid_from', sa.String(), nullable=False),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('evidence_reference', sa.String(), nullable=False),
    sa.Column('quality_status', sa.String(), nullable=False),
    sa.Column('quality_messages', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.CheckConstraint('normalized_value IS NULL OR normalized_value >= 0'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_entity_id'), ['entity_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.String(), nullable=False),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.CheckConstraint("role IN ('OWNS','OPERATES')"),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from'),
    sa.ForeignKeyConstraint(['company_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_entity_id'))

    op.drop_table('observations')
    with op.batch_alter_table('market_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_observations_instrument'))
        batch_op.drop_index(batch_op.f('ix_market_observations_effective_at'))

    op.drop_table('market_observations')
    op.drop_table('reviews')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    op.drop_table('sources')
    op.drop_table('runs')
    op.drop_table('entities')
    op.drop_table('audit')
    # ### end Alembic commands ###
