"""Add controlled master provenance candidate builds and exact temporal observations"""
from alembic import op
import sqlalchemy as sa

revision = 'ba950f257a0e'
down_revision = '5fa787f9511c'
branch_labels = None
depends_on = None

def upgrade():
    # Repair unnamed legacy checks before dependent candidate/detail tables exist.
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        table = sa.Table('observations', sa.MetaData(), autoload_with=bind)
        for constraint in list(table.constraints):
            if isinstance(constraint, sa.CheckConstraint) and not constraint.name:
                table.constraints.remove(constraint)
        table.append_constraint(sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_observation_interval'))
        table.append_constraint(sa.CheckConstraint('normalized_value IS NULL OR normalized_value >= 0', name='ck_observation_nonnegative'))
        with op.batch_alter_table('observations', copy_from=table, recreate='always'):
            pass
    else:
        names = {c['name'] for c in sa.inspect(bind).get_check_constraints('observations')}
        if 'ck_observation_interval' not in names:
            op.create_check_constraint('ck_observation_interval', 'observations', 'valid_to IS NULL OR valid_to >= valid_from')
        if 'ck_observation_nonnegative' not in names:
            op.create_check_constraint('ck_observation_nonnegative', 'observations', 'normalized_value IS NULL OR normalized_value >= 0')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('country',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('facility_type',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('source_snapshot',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.CheckConstraint('byte_size >= 0', name='ck_snapshot_size'),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('company',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('entity_alias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_name')
    )
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_alias_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_alias_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('entity_supersession',
    sa.Column('old_entity_id', sa.String(), nullable=False),
    sa.Column('new_entity_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint('old_entity_id <> new_entity_id', name='ck_supersession_distinct'),
    sa.ForeignKeyConstraint(['new_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['old_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('old_entity_id')
    )
    op.create_table('region',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'name')
    )
    op.create_table('retrieval_attempt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieval_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_attempt_run_id'), ['run_id'], unique=False)

    op.create_table('source_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('allowed_hosts', sa.JSON(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('retention', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('decided_at', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('permitted','review_required','restricted')", name='ck_source_access_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_access_source_id'), ['source_id'], unique=False)

    op.create_table('document_version',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_document_version_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['snapshot_hash'], ['source_snapshot.content_hash'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('evidence_build',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('specification', sa.JSON(), nullable=False),
    sa.Column('logical_output', sa.JSON(), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('commodity_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_code'], ['commodity.code'], ),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['type_code'], ['facility_type.code'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('source_document_relation',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'document_id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('build_id', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('reported_value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('evidence_reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('observation_id', sa.String(), nullable=True),
    sa.Column('review_id', sa.String(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['evidence_build.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_build_id'), ['build_id'], unique=False)

    op.create_table('observation_detail',
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=30, scale=6).with_variant(sa.String(40), 'sqlite'), nullable=True),
    sa.Column('normalized_unit', sa.String(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint("normalized_unit IS NULL OR normalized_unit IN ('t/year','MW','percentage')", name='ck_detail_unit'),
    sa.CheckConstraint('normalized_value IS NULL OR normalized_value >= 0', name='ck_detail_nonnegative'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_detail_interval'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    # Seed controlled references; preserve historical IDs and safe native dates.
    import json, unicodedata
    from uuid import uuid4
    from datetime import date, datetime, timezone
    from decimal import Decimal
    def rows(name):
        return bind.execute(sa.select(sa.Table(name, sa.MetaData(), autoload_with=bind))).mappings().all()
    def insert(table_name, **values):
        bind.execute(sa.Table(table_name, sa.MetaData(), autoload_with=bind).insert().values(**values))
    countries = {'AU': 'Australia', 'NO': 'Norway', 'IS': 'Iceland', 'CA': 'Canada', 'US': 'United States', 'BR': 'Brazil', 'QA': 'Qatar', 'SK': 'Slovakia', 'DE': 'Germany', 'FR': 'France', 'IN': 'India', 'CN': 'China', 'RU': 'Russia', 'AE': 'United Arab Emirates', 'BH': 'Bahrain', 'NZ': 'New Zealand', 'GB': 'United Kingdom', 'ZA': 'South Africa', 'JM': 'Jamaica', 'GN': 'Guinea', 'IE': 'Ireland', 'ES': 'Spain', 'GR': 'Greece', 'MZ': 'Mozambique', 'ID': 'Indonesia', 'MY': 'Malaysia', 'OM': 'Oman', 'SA': 'Saudi Arabia'}
    commodities = {'aluminium': 'Aluminium', 'alumina': 'Alumina', 'bauxite': 'Bauxite'}
    entities = rows('entities')
    for entity in entities:
        if not entity['country']:
            raise ValueError('Legacy entity lacks country; correct data before migration')
        countries.setdefault(entity['country'], 'Legacy country: ' + entity['country'])
        commodities.setdefault(entity['commodity'], 'Legacy commodity: ' + entity['commodity'])
    for code,name in countries.items(): insert('country', code=code, name=name)
    for code,name in commodities.items(): insert('commodity', code=code, name=name)
    for code,name in {'smelter': 'Primary aluminium smelter', 'refinery': 'Alumina refinery', 'bauxite_mine': 'Bauxite mine'}.items(): insert('facility_type', code=code, name=name)
    timestamp = datetime.now(timezone.utc).isoformat()
    regions = {}
    for entity in entities:
        if entity['kind'] == 'company':
            insert('company', entity_id=entity['id'])
        else:
            region_id = None
            if entity['region']:
                key = (entity['country'], entity['region'])
                if key not in regions:
                    regions[key] = str(uuid4())
                    insert('region', id=regions[key], country_code=key[0], name=key[1])
                region_id = regions[key]
            insert('facility', entity_id=entity['id'], country_code=entity['country'], type_code=entity['facility_type'], commodity_code=entity['commodity'], region_id=region_id)
        aliases = entity['aliases']
        if isinstance(aliases, str): aliases = json.loads(aliases)
        seen = set()
        for name in aliases:
            key = ' '.join(''.join(c if c.isalnum() else ' ' for c in unicodedata.normalize('NFKC', name).casefold()).split())
            if key and key not in seen:
                insert('entity_alias', id=str(uuid4()), entity_id=entity['id'], name=name, normalized_name=key, actor='migration', reason='Preserved legacy alias', created_at=timestamp)
                seen.add(key)
    snapshots = set()
    for doc in rows('documents'):
        if doc['content_hash'] not in snapshots:
            insert('source_snapshot', content_hash=doc['content_hash'], storage_reference=doc['content_hash'], byte_size=None)
            snapshots.add(doc['content_hash'])
        insert('document_version', document_id=doc['id'], snapshot_hash=doc['content_hash'], version=doc['version'])
        insert('source_document_relation', source_id=doc['source_id'], document_id=doc['id'])
    for obs in rows('observations'):
        value = None
        if obs['attribute']!='status':
            from decimal import localcontext
            factors={'t/year':Decimal(1),'kt/year':Decimal(1000),'Mt/year':Decimal(1000000),'MW':Decimal(1),'percentage':Decimal(1)}
            with localcontext() as precision:
                precision.prec=60
                value=Decimal(obs['reported_value'].replace(',',''))*factors[obs['reported_unit']]
                if value!=value.quantize(Decimal('0.000001')): raise ValueError('Legacy value exceeds supported fractional precision')
        if value is not None and (not value.is_finite() or value < 0 or value >= Decimal('1e24')):
            raise ValueError('Legacy normalized value outside exact numeric range')
        insert('observation_detail', observation_id=obs['id'], normalized_value=(str(value) if bind.dialect.name == 'sqlite' and value is not None else value), normalized_unit=obs['normalized_unit'], valid_from=date.fromisoformat(obs['valid_from']), valid_to=date.fromisoformat(obs['valid_to']) if obs['valid_to'] else None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_detail')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_build_id'))

    op.drop_table('candidate')
    op.drop_table('source_document_relation')
    op.drop_table('facility')
    op.drop_table('evidence_build')
    op.drop_table('document_version')
    with op.batch_alter_table('source_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_access_source_id'))

    op.drop_table('source_access')
    with op.batch_alter_table('retrieval_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_attempt_run_id'))

    op.drop_table('retrieval_attempt')
    op.drop_table('region')
    op.drop_table('entity_supersession')
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_alias_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_entity_alias_entity_id'))

    op.drop_table('entity_alias')
    op.drop_table('company')
    op.drop_table('source_snapshot')
    op.drop_table('facility_type')
    op.drop_table('country')
    op.drop_table('commodity')
    # ### end Alembic commands ###
