"""Record parser version on observations"""
from alembic import op
import sqlalchemy as sa

revision = 'c435d4e5fa97'
down_revision = '9a4e590703d9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parser_version', sa.String(), nullable=False, server_default='manual-v1'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    args = {}
    if bind.dialect.name == 'sqlite':
        table = sa.Table('observations', sa.MetaData(), autoload_with=bind)
        for constraint in list(table.constraints):
            if isinstance(constraint, sa.CheckConstraint) and not constraint.name:
                table.constraints.remove(constraint)
        names = {c.name for c in table.constraints}
        if 'ck_observation_interval' not in names:
            table.append_constraint(sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_observation_interval'))
        if 'ck_observation_nonnegative' not in names:
            table.append_constraint(sa.CheckConstraint('normalized_value IS NULL OR normalized_value >= 0', name='ck_observation_nonnegative'))
        args['copy_from'] = table
    with op.batch_alter_table('observations', schema=None, **args) as batch_op:
        batch_op.drop_column('parser_version')

    # ### end Alembic commands ###
