"""Record parser version on observations"""
from alembic import op
import sqlalchemy as sa

revision = 'c435d4e5fa97'
down_revision = '9a4e590703d9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parser_version', sa.String(), nullable=False, server_default='manual-v1'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('parser_version')

    # ### end Alembic commands ###
