"""Link curated asset identities to exact evidence"""
from alembic import op
import sqlalchemy as sa

revision = 'ce047394cadf'
down_revision = '6d0761b91504'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_evidence',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('evidence_reference', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_version.document_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'document_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_evidence')
    # ### end Alembic commands ###
